# =======================================================
# AliienItemBlacklist - Config
# =======================================================
# List of blacklisted items (make sure they are in caps)
blacklisted-items:
  - BEDROCK
  - BARRIER

# DO NOT under any circumstance touch this unless you are told to by the official support
config-version: 1