name: AliienItemBlacklist
version: '${project.version}'
main: com.aliiensmp.aliienItemBlacklist.AliienItemBlacklist
api-version: '1.21'
folia-supported: true

permissions:
  aliien.itemblacklist.*:
    description: Grants all AliienItemBlacklist permissions.
    default: op
    children:
      aliien.itemblacklist.bypass: true
      aliien.itemblacklist.reload: true
      aliien.itemblacklist.alert: true
      aliien.itemblacklist.edit: true
      aliien.itemblacklist.version-notify: true
  aliien.itemblacklist.bypass:
    description: Allows a player to pick up and interact with blacklisted items.
    default: op
  aliien.itemblacklist.reload:
    description: Allows a player to reload the config.
    default: op
  aliien.itemblacklist.alert:
    description: Receives a notification when someone handles a blacklisted item.
    default: op
  aliien.itemblacklist.edit:
    description: Allows a player to modify the blacklisted items list.
    default: op
  aliien.itemblacklist.version-notify:
    description: Receives a notification when there is a new plugin update.
    default: op